DPE-904 Update libraries and components versions to fix building/releasing. (#9)
* Upgrade charming action to v2.1.0

* Upgrade charming action to v2.1.1

*Update actions/checkout v2 -> v3

* Update charming-actions/check-libraries 1.0.3 -> 2.1.1

* Switch build/run-on 20.04 => 22.04 for charmcraft.yaml

Otherwise charmcraft cannot pack and publish new charm:

> Run canonical/charming-actions/upload-charm@2.0.0-rc
> /usr/bin/sudo snap install charmcraft --classic --channel latest/stable
> charmcraft 2.1.0 from Canonical** installed
> /usr/bin/sudo charmcraft pack --destructive-mode --quiet
> No suitable 'build-on' environment found in any 'bases' configuration.
> Full execution log: '/root/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20230103-140117.065549.log'
> Error: The process '/usr/bin/sudo' failed with exit code 1
> Error: Error: The process '/usr/bin/sudo' failed with exit code 1

It happens due to '--destructive-mode' in use, which means
"don't use a LXD container, just run the build on this host"
therefor build-on version in charmcraft.yaml must match GH CI 'ubuntu-latest'.